[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.9'

[profile.dojo]
solc = '0.8.9'

[profile.subscribee]
solc = '0.8.8'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config